/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('../src/components/window/chat/index.vue')['default']
    Chats: typeof import('../src/components/window/chat/index.vue')['default']
    FunctionalRemoteChat: typeof import('./../src/components/functional/remote-chat.vue')['default']
    FunctionalTestChat: typeof import('./../src/components/functional/test-chat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerminalHeader: typeof import('./../src/components/terminal/header.vue')['default']
    WindowChat: typeof import('./../src/components/window/chat/index.vue')['default']
    WindowChats: typeof import('../src/components/window/chat/index.vue')['default']
  }
}
